set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property PACKAGE_PIN Y9 [get_ports i_clk]

set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports i_rst]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports o_hsync]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS33} [get_ports o_vsync]
set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS33} [get_ports {o_red[3]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {o_red[2]}]
set_property -dict {PACKAGE_PIN Y10 IOSTANDARD LVCMOS33} [get_ports {o_red[1]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {o_red[0]}]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVCMOS33} [get_ports {o_green[3]}]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS33} [get_ports {o_green[2]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {o_green[1]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports {o_green[0]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {o_blue[3]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports {o_blue[2]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {o_blue[1]}]
set_property -dict {PACKAGE_PIN AA7 IOSTANDARD LVCMOS33} [get_ports {o_blue[0]}]

set_property PACKAGE_PIN T18 [get_ports i_left_down]
set_property PACKAGE_PIN R16 [get_ports i_left_up]
set_property PACKAGE_PIN N15 [get_ports i_right_down]
set_property PACKAGE_PIN R18 [get_ports i_right_up]
set_property IOSTANDARD LVCMOS33 [get_ports i_left_down]
set_property IOSTANDARD LVCMOS33 [get_ports i_left_up]
set_property IOSTANDARD LVCMOS33 [get_ports i_right_down]
set_property IOSTANDARD LVCMOS33 [get_ports i_right_up]
set_property PACKAGE_PIN T22 [get_ports {o_score_left[3]}]
set_property PACKAGE_PIN T21 [get_ports {o_score_left[2]}]
set_property PACKAGE_PIN U22 [get_ports {o_score_left[1]}]
set_property PACKAGE_PIN U21 [get_ports {o_score_left[0]}]
set_property PACKAGE_PIN V22 [get_ports {o_score_right[3]}]
set_property PACKAGE_PIN W22 [get_ports {o_score_right[2]}]
set_property PACKAGE_PIN U19 [get_ports {o_score_right[1]}]
set_property PACKAGE_PIN U14 [get_ports {o_score_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_score_right[0]}]
